paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  projects:
    path: _projects
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  imagecdn:
    staging: https://ed-rosa-dev.imgix.net
    production: https://ed-rosa.imgix.net
  social:
    - name: Twitter
      icon: twitter
      username: '@rosierichards'
      url: https://twitter.com/rosierichards
      desc: Follow us on Twitter
      share: true
    - name: Facebook
      icon: facebook
      username: ROSA Productions
      url: https://www.facebook.com/pages/ROSA-Productions/171821742900370?fref=ts
      desc: Like us on Facebook
      share: true
    - name: GitHub
      icon: github
      username:
      url:
      desc: Fork us on GitHub
      share: false
    - name: LinkedIn
      icon: linkedin
      username:
      url:
      desc: Connect with us on LinkedIn
      share: true
    - name: YouTube
      icon: youtube
      username:
      url:
      desc: Subscribe on YouTube
      share: false
    - name: Instagram
      icon: instagram
      username:
      url:
      desc: Follow me on Instagram
      share: false
    - name: Pinterest
      icon: pinterest
      username:
      url:
      desc: Follow me on Pinterest
      share: true
    - name: Vimeo
      icon: vimeo-square
      username:
      url:
      desc: Follow me on Vimeo
      share: false
  protocols:
    fb_image: /assets/logo.png
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: image/png
    twitter_image: /assets/logo.png
data_config: {}
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Europe/London
